### ISSUE TITLE
yaxis on the chipplot.py

### ISSUE THREAD

**Issue by devjunhong** [nicmcd/chips#1]
Hello I'm Junhong, 
I clone your repository and figure out yaxis not work. 
I found a problem that the regular expression on chipplot.py 43 line doesn't work properly.

My suggestion is 

m = re.findall('\d+', ytext)
exp = int(m[1])

I would like to contribute directly, but some reasons I couldn't, so I open this issue. 

Please look through it. 
Thanks

**Comment by nicmcd** [comment]
Thanks for your interest. Please tell me what the error is. What do you mean "doesn't work properly"? What is the current implementation not doing?

For contributing, please follow the standard Github approach of Fork, Commit, Push, Pull Request. 
[Forking](https://help.github.com/articles/fork-a-repo/)
[Pull Request](https://help.github.com/articles/creating-a-pull-request/)

**Comment by devjunhong** [comment]
Thank you for the link 
I made a pull request! so please check it :D
